# Site settings
title: StartupHouse Oakland
email: Hi@StartupHouseOakland.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: startuphouseoak

# Build settings
markdown: kramdown
